language: node_js

sudo: false

stages:
  - build
  - name: deploy
    if: tag =~ /^v\d+\.\d+\.\d+$/ AND repo = HaaLeo/vscode-timing


node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:postinstall

jobs:
  include:
    - stage: build
      script:
        - npm run compile
        - npm run tslint
    - stage: deploy
      before_deploy:
        - vsce publish -p ${VSC_PUBLISH_TOKEN}
        - vsce package
        - export RELEASE_PKG_FILE=$(ls *.vsix)
      script: skip
      deploy:
        provider: releases
        file_glob: true
        file: "${RELEASE_PKG_FILE}"
        api_key: ${Travis_CD}
        skip_cleanup: true
        on:
          tags: true
